baseURL = 'https://ebobrow.github.io/'
languageCode = 'en-us'
title = "Elliot's Blog"
theme = 'smol'

[params]
    mode="dark"
    subtitle = "\"Oh good, another blog by a theoretical CS student!\" - No one"
    dateFmt = "02.01.2006"
    customCSS = ["css/custom.css"]

# Header
[menu]
  [[menu.main]]
        identifier = "about"
        name = "About"
        url = "/about/"
        weight = 1

  [[menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts/"
        weight = 2 

  [[menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags/"
        weight = 3

# Footer
  [[menu.footer]]
        name = "Github"
        url = "https://github.com/ebobrow"
        weight = 1 

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'], ['$', '$']]

[caches]
  [caches.images]
    dir = ':cacheDir/images'
