baseURL = 'https://ebobrow.github.io/'
languageCode = 'en-us'
title = "Elliot's Blog"
theme = 'archie'

# pygmentsstyle = "monokai"
# pygmentscodefences = true
# pygmentscodefencesguesssyntax = true
[params]
	mode="dark"
	useCDN=false
	subtitle = "_\"Oh good, another blog by a theoretical CS student!\" --- No one_"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'], ['$', '$']]
